on: 
  push:
    paths:
    - 'hw1.Rmd'
name: Check Rmd Structure
jobs:
  test:
    runs-on: self-hosted
    container:
      image: ghcr.io/statprog-s1-2020/hw1-docker:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Structure
      run: |
        tpl = readRDS(".github/workflows/template.rds")
        checklist::quit_on_failure({
          parsermd::rmd_check_template("hw1.Rmd", tpl)
        })
      shell: Rscript {0}
